modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://github.com/MC-Expanded/Fancy-Tabs-Neo/issues" #optional

[[mods]] #mandatory
modId="fancytabsections"
version="6.2.1-FORGE-1.20.1"
displayName="Fancy Tab Sections"
displayURL="http://curseforge.com/minecraft/mc-mods/fancy-tab-sections"
logoFile = "icon.png"
mod_authors="wdiscute, Kaupenjoe, nanoattack, NicciCage"
description='''
A library to allow for easy control of Sections inside Creative Mode Tabs
'''

[[mixins]]
config="fancytabsections.mixins.json"

[[dependencies.fancytabsections]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[47.3,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.fancytabsections]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"